# premain启动会加载plugins下配置的插件目录, agentmain启动会加载dynamicPlugins下的active插件目录
# 插件的加载顺序如下：
#   1. 首先按照`plugins`中配置的插件顺序来加载默认插件。
#   2. 然后再按照`profile`配置的场景顺序来加载场景插件列表, 各场景的插件加载顺序也和配置文件中的顺序一致。
#   3. 如果`profiles`中的配置的插件已经在之前加载过, 则不再重复加载。
#   4. 不同插件的相同拦截点的字节码增强的生效顺序与插件加载顺序是一致的。
# plugins用于配置静态插件, premain启动时生效, 配置支持静态安装的插件, 不允许卸载
plugins:
  - template
# dynamicPlugins用于配置支持动态安装的插件, agentmain启动时生效, 允许卸载:
#  1. active类型插件将会主动启用
#  2. passive类型插件需通过指令或接口调用启用
dynamicPlugins:
  active:
#    - active-plugin
  passive:
#    - passive-plugin
